name: Host Service CI
on:
  push:
    branches:
      - 'main'
    paths:
      - '*.js'
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1.Checkout
      uses: actions/checkout@v3

    - name: 2.Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: csyeob/hostservice:${{ github.sha }}
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps: 
      - name: 1.Checkout
        uses: actions/checkout@v2
        with: 
          repository: 'csyeob/hostsvc-cd'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 2. Change Docker Tag
        run: |
          cat test.yaml | sed "s/image: csyeob\/node-app:.*/images: dangtong\node-app:${{ github.sha }}/g" hostservice-deploy.yaml
          git config --global user.email "csyeob@gmail.com"
          git config --global user.name "csyeob"
          git commit -am "triggered by github action"
          git push origin main

